# Deploy static site to GitHub Pages using the official Pages actions
name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./    # publish from repository root (index.html, style.css, script.js, images/)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
